version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:8080"
    environment:
      - FLASK_ENV=production  # 使用記憶體資料庫
      - SECRET_KEY=dev-secret-key-for-testing
      - PORT=8080
    volumes:
      - app_data:/app/instance
      - ./uploads:/app/uploads
      - ./app:/app/app  # 開發時程式碼熱重載
    restart: unless-stopped

volumes:
  app_data: